APT::FTPArchive::Release {
  Origin "refsprogs";
  Label "refsprogs";
  Suite "main";
  Codename "trixie";
  Architectures "amd64 arm64 armel armhf i386 ppc64el riscv64 s390x alpha hppa loong64 m68k powerpc ppc64 sh4 sparc64 x32";
#  Architectures "amd64 arm64 armel armhf i386 ppc64el riscv64 s390x hppa loong64 m68k powerpc ppc64 sh4 sparc64 x32";
  Components "main";
  Description "refsprogs APT repository";
};
