APT::FTPArchive::Release {
  Origin "refsprogs";
  Label "refsprogs";
  Suite "main";
  Codename "trixie";
  Architectures "amd64 arm64 armel armhf i386 ppc64el riscv64 s390x";
  Components "main";
  Description "refsprogs APT repository";
};
