APT::FTPArchive::Release {
  Origin "refsprogs";
  Label "refsprogs";
  Suite "main";
  Codename "main";
  Architectures "amd64 arm64 armel armhf i386 mips64el mips mipsel ppc64el s390x";
  Components "main";
  Description "refsprogs APT repository";
};
