Dir::ArchiveDir ".";
Dir::CacheDir ".";
TreeDefault::Directory ".";
TreeDefault::SrcDirectory ".";
Default::Packages::Extensions ".deb";
Default::Packages::Compress ". gzip bzip2";
Default::Sources::Compress ". gzip bzip2";
Default::Contents::Compress "gzip bzip2";

BinDirectory "dists/main/main/binary-amd64" {
  Packages "dists/main/main/binary-amd64/Packages";
  Contents "dists/main/main/Contents-amd64";
  SrcPackages "dists/main/main/source/Sources";
};

BinDirectory "dists/main/main/binary-arm64" {
  Packages "dists/main/main/binary-arm64/Packages";
  Contents "dists/main/main/Contents-arm64";
  SrcPackages "dists/main/main/source/Sources";
};

BinDirectory "dists/main/main/binary-armel" {
  Packages "dists/main/main/binary-armel/Packages";
  Contents "dists/main/main/Contents-armel";
  SrcPackages "dists/main/main/source/Sources";
};

BinDirectory "dists/main/main/binary-armhf" {
  Packages "dists/main/main/binary-armhf/Packages";
  Contents "dists/main/main/Contents-armhf";
  SrcPackages "dists/main/main/source/Sources";
};

BinDirectory "dists/main/main/binary-i386" {
  Packages "dists/main/main/binary-i386/Packages";
  Contents "dists/main/main/Contents-i386";
  SrcPackages "dists/main/main/source/Sources";
};

BinDirectory "dists/main/main/binary-mips64el" {
  Packages "dists/main/main/binary-mips64el/Packages";
  Contents "dists/main/main/Contents-mips64el";
  SrcPackages "dists/main/main/source/Sources";
};

BinDirectory "dists/main/main/binary-mips" {
  Packages "dists/main/main/binary-mips/Packages";
  Contents "dists/main/main/Contents-mips";
  SrcPackages "dists/main/main/source/Sources";
};

BinDirectory "dists/main/main/binary-mipsel" {
  Packages "dists/main/main/binary-mipsel/Packages";
  Contents "dists/main/main/Contents-mipsel";
  SrcPackages "dists/main/main/source/Sources";
};

BinDirectory "dists/main/main/binary-ppc64el" {
  Packages "dists/main/main/binary-ppc64el/Packages";
  Contents "dists/main/main/Contents-ppc64el";
  SrcPackages "dists/main/main/source/Sources";
};

BinDirectory "dists/main/main/binary-s390x" {
  Packages "dists/main/main/binary-s390x/Packages";
  Contents "dists/main/main/Contents-s390x";
  SrcPackages "dists/main/main/source/Sources";
};

Tree "dists/main" {
  Sections "main";
  Architectures "amd64 arm64 armel armhf i386 mips64el mips mipsel ppc64el s390x";
};
